[workspace]
members = ["crusader", "crusader-lib", "crusader-gui"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[patch.crates-io]
freetype-sys = { git = 'https://github.com/Zoxc/freetype-sys.git' }
expat-sys = { git = 'https://github.com/Zoxc/libexpat.git' }
