[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
library = { path = "../library" }
toml = "0.5.9"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.18.2", features = ["full"] }
eframe = "0.18.0"