[package]
name = "crusader"
version = "0.1.0"
edition = "2021"

[dependencies]
crusader-lib = { path = "../crusader-lib" }
clap = { version = "3.1.18", features = ["derive"] }
clap-num = "=1.1.1"
env_logger = "0.10.0"
