[workspace]
members = ["crusader", "crusader-lib", "crusader-gui-lib", "crusader-gui"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "symbols"

[patch.crates-io]
winit = { git = "https://github.com/Zoxc/winit", branch = "crusader" }
