name: ci

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Build
      run: cargo build
    - name: Lint
      run: cargo clippy --all -- -D warnings
    - name: Format
      run: cargo fmt --all -- --check